### ISSUE TITLE
Relative image path in WebView

### ISSUE THREAD

**Issue by romovs** [trueinteractions/tint2#104]
I am having issues using images with relative URIs in the WebView

Works: ```<img src="file:///C:/tint2_test/image.png" />```
Doesn't work:```<img src="image.png" />```

html, images, and tint binaries are all located in the tint2_test folder.
The application is started from within that folder with "tint.exe main.js"

Running on Windows 7 with tint2 build from the latest master.

**Comment by trevorlinton** [comment]
@romovs 

I appreciate the bug report, it helps when we have users actively reporting problems so we can help make a better product. 

This has been fixed with https://github.com/trueinteractions/tint2/commit/f23a04bc4a819da5db41dfebcfff9206bef3c0a8 if you continue to have issues, feel free to reopen.

This will be included with release 2.1.4 (later this evening).
