### ISSUE TITLE
Textured window behavior inconsistent on Windows

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint2#108]
When using the ``textured`` property of a window set to ``true``, I do not see a difference. Looking at the documentation, I'm not sure why the behavior of ``textured`` on Windows isn't the "glass" effect, such as here https://github.com/trueinteractions/tint/blob/master/src/browser/native_window_win.cc#L396
There seems to be commonality between a "textured" window in OS X and rendering over the "glass" or frame in Windows.

**Comment by trevorlinton** [comment]
We'll take a look into it.  Are you on Win8 or win7?

**Comment by trevorlinton** [comment]
@JohnLouderback We've fixed this.

Heres the appearance with textured = true on win7/win8:

![screen shot 2015-04-04 at 2 52 49 pm](https://cloud.githubusercontent.com/assets/3111873/6994523/6ff20bb0-dada-11e4-81b6-464f9095491f.png)

![screen shot 2015-04-04 at 2 52 20 pm](https://cloud.githubusercontent.com/assets/3111873/6994528/81634684-dada-11e4-94fd-ad9b5397a789.png)

This is fixed with this commit and will be in the next release: https://github.com/trueinteractions/tint2/commit/2134842dd3c16335b200549b904937120443833e
