### ISSUE TITLE
"Can't allocate a new block for a pasteboard" 

### ISSUE THREAD

**Issue by tzmartin** [trueinteractions/tint2#113]
Hi. Thanks for creating Tint.

Seems a bug exists when trying to access the pasteboard from a webview to the Tint context. I'm getting an error when invoking the context menu (right click) or firing events between contexts.  

I wonder if this is related to this Chromium bug ticket: [https://code.google.com/p/chromium/issues/detail?id=467296](https://code.google.com/p/chromium/issues/detail?id=467296).

Simple test case (node v0.12.2, Mac 10.10.3):

```
require('Common');

var win = new Window();
var webview = new WebView();
win.appendChild(webview);
webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = "https://www.google.com";
win.visible = true;
```
1. Right click on the search box.
2. Output:
```
tint[53124:495816] Can't allocate a new block for a pasteboard. Creation of a new Pasteboard will fail.
```

Also, do you have thoughts on how best to interface with NSPasteboard for webviews?  Currently testing marshaling via the event bus.  Working on a text editor.

Best

**Comment by trevorlinton** [comment]
Interesting, i'm unable to replicate it (also on 10.10.3) but searching around some of the forms i visited had referenced an issue with applications that attempt to capture paste events, not sure if this is any clue as to what be going on.

1. If its a plugin, we can rule that out really quickly to see if WKWebView has plugins enabled, run:
```javascript
require('Common');

var win = new Window();
var webview = new WebView();
win.appendChild(webview);
webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = "https://www.google.com";
win.visible = true;
setTimeout(function() {
	console.log(webview.native('configuration')('preferences')('plugInsEnabled'));
},100);
```

It should spit out true or false depending on whether the plugins are enabled. 

2. It could possibly be some sort of side effect to not having a menu installed.  Paste operations go to the controller on the applications, which then sends it to the key NSWindow in the event chain, the NSWindow then looks to see what menu items are enabled and responds to paste events (e.g., cmd-v/cmd-c).  You can add global support for copy/paste by adding a default standard menu as shown in the examples here: http://www.trueinteractions.com/tint2/docs/Menu.html#Menu

I'll keep testing to see if i can replicate this, if you find any clues let me know.

**Comment by tzmartin** [comment]
Thanks for your time looking into this.  You pointed me in the right direction.  Tested for WKWebView plugins and tested with a valid menu, but nada.  All signs pointed to my local environment.  Happy to say I found the fix.  Updated command line tools to 10.10 and latest Xcode.  Tests passed.

Perhaps I should have tested on my other machine to verify env. 

Worth noting, initially I couldn't trace the segfault until (at some point) the NSPasteboard statement showed up.  I tried node inspector, Chromium logs, etc.  I tried downgrading to a previous builds from both local compilation and hosted releases.  Hard to inspect the runtime.  Any recommendations on debugging the runtime?

Thanks!

**Comment by trevorlinton** [comment]
Hm, we use node inspector when developing the internals and don't have any issues.  The one caveat is if there is a callback from a native object into javascript and we don't have a try/catch and theres a javascript error that bubbles up (uncaught) back into the native object.  When that happens its proxied into a native exception and if the native component doesnt catch it theres a seg fault. 

Traditionally we've managed this by always wrapping our callbacks from native objects in a try catch that prints the stack error then exits, there may be some corners and situations that aren't covered however.

You can see what I mean here: https://github.com/trueinteractions/tint2/blob/master/modules/WebView/WebView_mac.js#L15

The policy handler (what decides when a page loads) is called from the WKWebView object in OSX. If an error were to occur without the try catch statement it'll bubble back up to WKWebView and USUALLY a Objective-C stack trace will happen, however in some cases we see segmentation faults mostly due to the entire parent chain not handling the error.

Are you unable to get node-inspector to run at all? or was it unable to catch that an error was being thrown?

**Comment by tzmartin** [comment]
Thanks for the feedback and clarity. Similar workflow here and approach.  Yea, node inspector was running but crashing hard and failing to catch the event.  I couldn't see any specific logs or dumps, except for the ```RangeError``` statement.  I'm also using try catch blocks with a stack trace and using window.error events that serializes WebView logs.  Works well unless until it seg faults.

**Comment by trevorlinton** [comment]
@tzmartin I went through quite a few examples and haven't been able to have any issues with node inspector on osx and windows, i then realized i had modified parts of the node-inspector script a very long time ago to get it to work for me.  

The short of it (to use node-inspector, or any other node-esq tool) is to just run tint before it, e.g., instead of: 

```javascript
node-inspector somescript.js arguments..
```

run

```javascript
tint /usr/local/bin/node-inspector somescript.js arguments..
```

I've also added on https://github.com/trueinteractions/tint2/commit/f11f7d37cc630ca340da5b4049ada7041d30d6ed a new tool out in v2.1.13 (due today/tomorrow) to make this a bit less painless, it just adds the command line tool tntdbg that does some checks to make sure everythings setup properly then launches node inspector/node debugger. It's not necessary but makes it easier to work with.  

As for the remaining issues on this thread i'm not sure if theres any action items for me.  If you feel that some or any of these parts haven't been well addressed feel free to reopen.

Thanks,
Trevor
