### ISSUE TITLE
No maximize event for windows on Windows

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint2#129]
I realize there's no truly equivalent concept on OS X, but it would be very convenient to have an event fired for when a window is maximized in Windows.

**Comment by JohnLouderback** [comment]
My apologies. I just looked at the source code and there is a maximize event on Windows, it just wasn't in the documentation.

**Comment by trevorlinton** [comment]
@JohnLouderback It's undocumented due to OSX not having a maximize event, however OSX does have a "click" event for maximizing and a "zoom" event, the composite of which is semantically almost the same as windows maximize.  I added the maximize event to OSX (i've been meaning to sort out the differences in semantic between the two and add it anyway) on commit https://github.com/trueinteractions/tint2/commit/98590ccfe3bcd58e711d30974bde99405cdea4a3

This will be available on OSX and in the docs for the 2.1.14 release.

Thanks,
Trevor
