### ISSUE TITLE
Can't get StatusBar icon position

### ISSUE THREAD

**Issue by dchapkine** [trueinteractions/tint2#135]
Hi,

I try to position a window relative to the StatusBar icon. 

After checking the docs, i can't find a way to get the position of the tray icon.

It would be cool to have this information on `statusBar.x  statusBar.y` or as click callback param:

```
statusBar.addEventListener("click", function(e) {
	console.log(e.screenX, e.screenY);
});
```

But maybe there is already a way to do this ?

Thanks

**Comment by JohnLouderback** [comment]
There may be APIs for this on OS X, but to the best my knowledge, Windows offers no position information on its icons in either the task bar nor the system tray. Not sure if that's helpful to your question, but I figured I'd put it out there.

**Comment by trevorlinton** [comment]
@dchapkine Yes, well sort of, John is right in that it there really isn't a good solution (if any) on Windows so its only supported on OSX. 

You can use the StatusBar "custom" property . It allows you to use any Control object as your icon for the status bar. It unfortunately however is not supported on Windows, which is why it isnt documented. 

If you just wanted to show a standard image you could do:

```javascript
var imageWell = new ImageWell();
imageWell.image = "yourfile.png"
imageWell.width = 22;
imageWell.height = 22;

imageWell.on('rightmousedown', function() { /* do something for right mouse down */ });
imageWell.on('mousedown', function() { /* do something for left mouse down */ });

var statusBar = new StatusBar();
statusBar.custom = imageWell;
```

For the left mouse down you could have it show a window:

```javascript
var win = new Window();
var imageWell = new ImageWell();
imageWell.image = "yourfile.png"
imageWell.width = 22;
imageWell.height = 22;

imageWell.on('mousedown', function() {
  var bounds = imageWell.boundsOnScreen;
  win.x = bounds.x;
  win.y = bounds.y;
  win.visible = true;
});

var statusBar = new StatusBar();
statusBar.custom = imageWell;
```

I should warn I haven't tested this in a while.. and it isn't unit tested.  So it might not woorrk.... You'll need to play around a bit and see what you can come up with, i'll try and put together a more formal example when i have a second.

**Comment by trevorlinton** [comment]
So, it does work. You just have to add ``require('Common')`` to the top of both examples, i forget my own boilerplate code sometimes :).  

Infact I had a lot of fun using pop-overs with statusbars:

```javascript

require('Common');
var popOver = new PopOver();
var webview = new WebViews ();
webview.left = webview.right = webview.top = webview.bottom = 0;
popOver.appendChild(webview);
var imageWell = new ImageWell();
imageWell.image = "./tools/tint.png"
imageWell.width = 22;
imageWell.height = 22;

imageWell.on('mousedown', function() {
  webview.location = "https://github.com/trueinteractions/tint2/";
  popOver.open(imageWell, 'bottom');
});

var statusBar = new StatusBar();
statusBar.custom = imageWell;
```

And I found out we can actually support this on Windows:

https://msdn.microsoft.com/en-us/library/System.Windows.Forms.NotifyIcon(v=vs.110).aspx

I didn't notice the first time around that I hadn't clicked the "inherited" checkbox.  It turns out you can place any IContainer (essentially all Tint controls on Windows) into the system tray on windows as well.  I'll leave this open and slate adding back 'custom' as an officially supported property for 2.1.16.

Thanks @dchapkine @JohnLouderback

**Comment by dchapkine** [comment]
@trevorlinton thank you for all this examples

> It turns out you can place any IContainer (essentially all Tint controls on Windows) into the system tray on windows as well. I'll leave this open and slate adding back 'custom' as an officially supported property for 2.1.16

Awesome !

One thing that would be nice to have is to know when user clicked outside of the popover. Because most of the time when this happens you want to autoclose the popover.

This option will also be useful for a window object and could be implemented as a "click-outside" event on WIndow and Popover objects ?

In my case i use a window instead of popover because sometimes when i close a Popover i have a small visual glitch on OSX (it hides, then it shows for something like 100ms, then it hides again, if i focus another window and retry, the issue disappears).

Plus using a window instead of popover gives you more "design freedom".

Here is the code to reproduce the issue with popover glitch:
```
require('Common');

application.exitAfterWindowsClose = false;

var isPopoverOpened = false;
var popOver = new PopOver();
var webview = new WebView();
webview.left = webview.right = webview.top = webview.bottom = 0;
popOver.appendChild(webview);
var imageWell = new ImageWell();
imageWell.image = "./tint.png"
imageWell.width = 22;
imageWell.height = 22;

imageWell.on('mousedown', function() {

  if (isPopoverOpened)
  {
	//webview.location = "https://github.com/trueinteractions/tint2/";
  	popOver.open(imageWell, 'bottom');
  }
  else
  {
  	popOver.close()
  }

  isPopoverOpened = !isPopoverOpened;
});

var statusBar = new StatusBar();
statusBar.custom = imageWell;
```

When i use my own logic using transparent WIndow instead of Popover i don't have this issue. 


Thanks !

**Comment by dchapkine** [comment]
Re,

The only issue that remains here is the ability to know when the popover or window loses focus to be able to close it.

**Comment by trevorlinton** [comment]
This has been fixed, it however requires a slightly different approach, the example above (with all of the focus events) works in OSX and Windows:

```javascript
require('Common');

application.exitAfterWindowsClose = false;

var isPopoverOpened = false;
var popOver = new PopOver();
var webview = new WebView();
webview.left = webview.right = webview.top = webview.bottom = 0;
popOver.appendChild(webview);

var statusBar = new StatusBar();
statusBar.image = "./tools/tint.png"
statusBar.on('click', function() {
  // application.native('activateIgnoringOtherApps', true);
  popOver.open(statusBar, 'bottom');
});
```

If you have any other concerns or questions feel free to re-open this.
