### ISSUE TITLE
Can't set clipboard value (crash)

### ISSUE THREAD

**Issue by dchapkine** [trueinteractions/tint2#138]
Looks like System.clipboardSet tryes to free a null pointer somewhere.

code:
```
require('Common');

var v = System.clipboardGet("text");
console.log(v);
System.clipboardSet("tint", "text");
```

output:
```
<Buffer@0x7fec8a008298 74 69 6e 74>
tint(4458,0x7fff7280b300) malloc: *** error for object 0x7fec8a008410: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

On OSX 10.10.3  latest tint 2.1.15

@see https://www.trueinteractions.com/tint2/docs/System.html#clipboardSet

BTW:   "system" is used in documentation, but only "System" works for me

**Comment by trevorlinton** [comment]
@dchapkine Once again thanks for reporting this.  It seems the GC collection was occuring, afterwhich the clipboard data would be freed, when OSX went to free it the system sort of caput.  It's now fixed with a unit test.

This will be available in 2.1.16 on Monday, and per usual, reopen this if you have additional problems.
