### ISSUE TITLE
Feature request: container.appendChildAt

### ISSUE THREAD

**Issue by cesarandreu** [trueinteractions/tint2#147]
Currently, if you want to add a child to the container in a specific position, you need to copy `container.children`, add the child to your copy, remove all the children from the container, and then call `container.appendChild(childrenArray)`.

It seems that on OS X you could use [addSubview:positioned:relativeTo:](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSView_Class/index.html#//apple_ref/occ/instm/NSView/addSubview:positioned:relativeTo:). I'm not sure about Windows, since I have no clue how it works, but if you pointed me to the relevant documentation I think I could figure it out. 

Being able to append a child at a specific index position would be convenient. I'm fooling around with wrapping tint2 and using it as a react renderer.

**Comment by trevorlinton** [comment]
@cesarandreu Appreciate the pull request earlier, i'll add this to 2.1.18, if you have any other thoughts feel free to add them as feature requests in our bug tracker (or, submit a PR!).

If you do submit a PR, know that unless there are unit tests and functional test coverage for all features/options on both windows and osx we generally leave it "undocumented" so users don't get too comfortable using it.  There's actually quite a few things on the Window class that are not documented as theres really no good windows/osx compliment. 

Also, just for fun, the control used for adding children in .NET/MS world is: https://msdn.microsoft.com/en-us/library/system.windows.controls.panel.children(v=vs.110).aspx Instead of using .Add we'll just need to use .Insert (https://msdn.microsoft.com/en-us/library/ms590019(v=vs.110).aspx).  Pretty simple fix.

This will be out in the next 2.1.18 release due tomorrow.

Thanks Again!

**Comment by trevorlinton** [comment]
Fixed on https://github.com/trueinteractions/tint2/commit/a2aac18f0d9c36d275206b99ae04d8a72ea526a0 Feel free reopen if you continue to have issues.

**Comment by cesarandreu** [comment]
Ohh, awesome :D. Thank you for the super fast release!
I was planning on trying to do a PR but I guess I was too slow.
