### ISSUE TITLE
Detect OSX Yosemite dark mode switch

### ISSUE THREAD

**Issue by dchapkine** [trueinteractions/tint2#150]
Hi,

How can i detect if i am in dark mode on Yosemite ?

The reason i ask this is because Apple rejected my test app from appstore because i don't change systray icon when user switches to dark mode :))

I tested ImageWell.image attribute and it does change the image at runtime, the only missing thing now is to figure out how to detect display mode switch in tint. It should be an event because the mode can be changed back to normal, and i have to detect it too.

Now i would totally understand that you dont want to add this into core, in that case maybe you could show us what is the recommended file structure of a "tint plugin" ? So people can implement reusable features like this one in a standard, cross-platform and distributed way without "polluting" the core ?  I guess a tint plugin is just a nodejs package with 2 implementations like this: https://github.com/trueinteractions/tint2/tree/master/modules/Button ?

Thanks

**Comment by dchapkine** [comment]
Interesting read about "image templates" on OSX: 
http://stackoverflow.com/questions/24623559/nsstatusitem-change-image-for-dark-tint#answer-24644754

maybe this is a better way to deal with mode switch directly inside tint instead of watching for dark mode change event ?

@trevorlinton what do you think ?

**Comment by trevorlinton** [comment]
@dchapkine So the issue's a bit complicated, to fix this we could support image "templates", however it appears OSX would like to get rid of using these types of templates and switch to using the NSStatusBar's "button" which allows you to have finer grained control over rendering modes, they however have yet to publicly allow use of it (hopefully in el Capitan they will).  This means they reject apps but provide no real clear way to fix the problem for interim.  

My gut says if your app used NSPopOver's with NSStatusItem's then they're fine with apps accessing the button context.  So we might just go that route, although its still a private API and risky. 

The other option is just to provide an event when the visuals of the system switch. We could add an event for this, or do a plugin like you suggest. 

If you're interested in doing a plugin for Tint, it can be distributed just like a regular NPM module (see npmjs.org).   As an example here's a Tint plugin for Windows that uses Chrome instead of IE as its webview: https://github.com/trueinteractions/tint-chromium (here's the NPM module:  https://www.npmjs.com/package/chromium).

To install modules its as easy as doing ```npm install <plugin>``` then using ```require('<plugin>')``` within your source code where you need it. You can read more about NPM and node modules online.

We'll add a notification to the Application class to indicate if the appearance/visual has changed, for now, we'll have to be somewhat generic about it, e.g., "dark" or "light" and perhaps fire the same event on Windows depending on if the default chromatic shell color changes from dark to light.  Shouldn't be too difficult, can probably work it into the next release.

Thanks,
Trevor

**Comment by trevorlinton** [comment]
FYI,

This wont notify you when changes have occured, but if you need to know if OSX is running in "Dark" or "Light" mode you can use:
```javascript
var $ = process.bridge.objc;
var mode = $.NSUserDefaults('standardUserDefaults')('stringForKey',$("AppleInterfaceStyle")).toString();
if(mode === "Dark") { ... }
else { ... }
```

It doesnt appear there's an easy way of being notified when the appearance changes but i'll keep looking.

**Comment by trevorlinton** [comment]
@dchapkine We've added the ability to detect appearance changes, a new event 'appearance-changed' is now on the Application object, in addition we've added application.appearance that returns "light" and "dark".  This will be included in the release next monday.

Feel free to reopen this is you're still having issues.

**Comment by dchapkine** [comment]
@trevorlinton Great, thanks again !
