### ISSUE TITLE
Drop files to tray icon or app icon

### ISSUE THREAD

**Issue by dchapkine** [trueinteractions/tint2#151]
Is it possible to get list of files dropped on the systray icon as well as on app icon in the dock ?

I guess it should use the same event as here: #148 

```
application.addEventListener('open', onDrop);
```

**Comment by trevorlinton** [comment]
@dchapkine This is fixed with commit https://github.com/trueinteractions/tint2/commit/b3cd20b27d665e5a44af137dc3ae7a4736026f54 and will be in next 2.1.20 release next monday.

The fix only resolves the issue on Windows, on OSX you'll need to add the CFBundleDocumentTypes to the Info.plist (easiest to modify it after you bundle your application with XCode).  We'll add document types to the tntbuild commercial version.   

As an oddity, programmatically we can register file types and scheme's but dragging and dropping completely ignore the system file types database and only look at the bundle types. Curious..

Feel free to reopen if you have issues.
