### ISSUE TITLE
OS X message passing

### ISSUE THREAD

**Issue by mark1ewis** [trueinteractions/tint2#171]
Calling WebView.postMessage () on OS X appears to be buggy and not work except with extremely simple messages, at least with the 2.2.1 build on OS X El Capitan.  I haven't figured out the exact rules, but plain string messages are not delivered if they contain newlines, so for example this message is never received:

`webview.postMessage("This contains\n a newline");`

It is also doing some weird escaping, so if I send a JSON.stringified object that contains quotation marks, the quotation marks are escaped when sending the message, but when the message is received the quotation marks have been unescaped, so the JSON message is invalid and cannot be parsed.

I was trying to port a node-webkit app over to tint and finally gave up because I couldn't get the messages to get from node context to webview context; I tried base64-encoding the messages but they still didn't go through (length limit?), and other hacks like trying to use `webview.execute("var msg = 'XXX';")` didn't work either.

**Comment by trevorlinton** [comment]
Partially fixed with commit https://github.com/trueinteractions/tint2/commit/7ae97010a8d2678c263061a35dd3080ea4485c72

It appears there's issues with a new line being passed through, escaping them helps alleviate these issues.  There doesn't appear to be any problems passing large amounts of base64 data through, i tested this and was able to pass through 18mb.

I'll continue to investigate the escaping, it appears its not working properly and causing JSON encoded strings to fail.  Thanks for reporting this.

**Comment by trevorlinton** [comment]
Fixed with 21446a5. 

This will be in the next release (v2.2.2) due out Oct. 26th.  Feel free to reopen if you continue to have problems.
