### ISSUE TITLE
Native compiling into single executable?

### ISSUE THREAD

**Issue by tzmartin** [trueinteractions/tint2#178]
Just curious if there are plans to support compiling into native binaries (ie, [nexe](https://github.com/jaredallard/nexe) or [enclosejs](http://enclosejs.com/))?

**Comment by trevorlinton** [comment]
@tzmartin There is already support for compiling into native binaries, tntbuild does just this.  Although nexec and enclosejs are both made to produce CLI tools, not applications, which makes tint a bit different in both what's required of us and the result.

For Mac OSX we produce .app, which is an Apple version of an application (the exact same that xcode or any other compiler would produce).

For Windows we produce an executable, with resources, fairly similar to what others produce.  Tint (Commercial) also does a few other things.  We protect your source code from modifications by allowing you to code sign it. Code signing is natively supported by OSX and Windows to protect your applications. If anyone should modify the application or any of its resources the application fails to launch (enforced not by Tint, but by OSX and Windows).  Secondly, we obfuscate source code to prevent IP theft, or at least, deter it (similar to how websites protect their sources). 

This is not fullproof.  And don't believe the nexe, enclose js or V8 snapshots can completely encrypt or protect or fully protect anything.  Even native applications built in C++, C# and objective-c can be decompiled with relative ease. Xcode and Visual Studio both contain tools to do just this (mostly for debugging, not malicious reasons).  The reason i'm saying this is there's no concrete way of protecting distributed sources.  At all, anything you read insisting it is I would love to see their evidence.  This is a problem every company has been dealing with in the software space since the beginning of Photoshop "warez" cracks.

There are a few ways to protect your software. 1)  Use server side systems to complete sensitive transactions.  2) Do not embed any keys or data within your source code, fetch it from another source that requires an authentication (Either built in to the OS or ask for it).  3) Use obfuscation techniques such as uglify (or Tint Compiler) to prevent people from easily reading/replicating sources.  4) Use code signing to protect your application from being modified once distributed. 5) Use encryption of sensitive data for users and do not store the key in your application but the system key chain (we have tools for this if you don't know how).

I hope this helps answer you questions, if I was off base with my response, please let me know.

Thanks,
Trevor

**Comment by tzmartin** [comment]
Thanks for your feedback. Really appreciate it.  I understand the limitations and concerns around protecting binary code.  I'm interested in using V8 snapshots to "compile" static binaries that are linked to the JS context, similar to nw's implementation: [https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot](https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot).

Wondering if it's to possible (or planned) to load static binaries into the Tint context?

```
require('nw.gui').Window.get().evalNWBin(null, 'binary.bin');
```

And, perhaps for a different discussion.. but how could we add native dependencies to the Tint?

I'll reach out about commercial support.
