### ISSUE TITLE
Change window titlebar color

### ISSUE THREAD

**Issue by voronianski** [trueinteractions/tint2#52]
Is it possible to change color of window tilte bar?

```javascript
require('Application');

var Window = require('Window');

var appWin = new Window();
appWin.title = 'My title';
appWin.backgroundColor = '#000';
```

Maybe add smth like `textColor` property into https://github.com/trueinteractions/tint2/blob/master/modules/Window/Window_mac.js ?

**Comment by voronianski** [comment]
@trevorlinton unfortunately there are still no way to customize window's look

- Background color is not working when appending `WebView` to `Window` 

<img src="https://dl.dropboxusercontent.com/u/100463011/window-background-color.gif" width="500">

```javascript
setTimeout(function (argument) {
  win.appendChild(view);
}, 3000);
```

- First and second methods https://github.com/trueinteractions/tint2/issues/52#issuecomment-57585049 have too much cons right now (e.g. border radius doesn't work on `WebView` on frameless window)

- The only hope is that 3rd solution will implemented soon :)
> My personal favorite, is you can extend the "client area" (e.g., area you're allowed to draw in) to the title bar area. With this you would simply set the titlebar to blank then create a new text object and then simply center it on the frame in the middle. The only loss on this is you can't use title icons or document icons (or document menus in the titlebar). But few applications do use these.

**Comment by trevorlinton** [comment]
@voronianski Just as a side note if you set the left/right/top/bottom values to '2' (instead of 0, 1 still causes the same effect) it retains the background of the window. (not really sure why, still looking into this).

**Comment by trevorlinton** [comment]
@voronianski I've added the ability to customize the window (extending the client area, etc).  Note these new styling properties are not yet "officially" supported until I can find more fall-backs for pre-yosemite and add in theme support for Windows.

```javascript
require('Common');
var win = new Window();
win.backgroundColor = 'rgba(0,0,0,1)';
win.extendIntoTitle = true;	// Extend where you normally draw into the 
							// window "frame" below its buttons
win.titleTransparent = true; // Make the titlebar transparent, 
							 // otherwise "blur" effect or washout occurs.
win.titleVisible = true; // The titlebar can be disabled (either true or false)
win.appearance = "dark"; // (can be "light", "dark", "aqua", or "vibrant")
win.title = "Im a dark window.";
var box = new Box();
box.borderRadius = 5.5;
box.borderColor = 'rgba(0,1,0,1)'; // bright green.
win.appendChild(box);
box.left=box.right=box.top=box.bottom = 0;
win.visible = true;
```

The new "extendIntoTitle" will extend the content area into (under) the title and window frame buttons. Note that if you do not set the title to be transparent the default "appearance" will be applied to the title bar.  The "titleTransparent" simply removes any titlebar styling and makes it inherit whats behind it. The "titleVisible" removes the title bar if set to false (just the title text) and integrates toolbars into where the titlebar would be.

Finally there's the "appearance" property, which can be set to "light", "dark", "normal" or "vibrant".  The appearance is dictated by the OS.  On OS X, "normal" reverts back to the mavericks appearance, the default, "vibrant" sets the new Yosemite feel.  and "light" and "dark" simply set the window to either have a light hue or dark hue.  The light and dark settings are important as it dictates how the buttons, text and other native OS elements render in the title and window frames (and their hover states).  For example, if set to "dark" no text or icons will ever render as "black" but as "white" or its contrast.

Play around with it, hope it helps. I'm going to leave this open until its supported in Windows. 

BTW - Please - Please - Please, if you file any new bug reports and are using ANY of these properties, point out to me that you're using them or use them in the code examples you provide.  It helps since we don't have any unit tests for this yet.

**Comment by voronianski** [comment]
@trevorlinton thanks, that's very cool! However there are few issues with `appearance`:

- `dark` appearance makes window not dark but white :) also title is shown only after click on its' place

```javascript
require('Common');

application.exitAfterWindowsClose = true;

var win = new Window();

win.title = 'Telepath Title';
win.appearance = 'dark';
win.visible = true;
```

<img src="https://dl.dropboxusercontent.com/u/100463011/window-appearance-bug.gif" width="550">

- with `win.extendIntoTitle = true;` window style becomes very strange

```javascript
require('Common');

application.exitAfterWindowsClose = true;

var win = new Window();

win.extendIntoTitle = true; // breaks style
win.title = 'Telepath Title';
win.appearance = 'dark';
win.visible = true;
```

<img src="https://dl.dropboxusercontent.com/u/100463011/window-appearance-bug2.png" width="550">

**Comment by trevorlinton** [comment]
@voronianski It seems setting the appearance to dark or light causes OS X to stop drawing or clearing the background frame of the window (and you'll see random bitblt data rendered from whatever is in the allocated memory space)..  Thus the oddities you'll see when using "dark" or "light" themes.  

This however can be corrected by simply setting the background color on the window. Do you have a preference on how to handle this situation?  We could easily default a background color if the user selects dark or light themes. 

Just to be clear OS X defines dark and light themes not like Windows; e.g., It does not consider these themes as color palettes to apply; but rather it provides guidelines for what the system should pick for system rendered font colors, and other widgets placed.  It would make sense then to simply default the background to a dark gray on "dark" and a lighter control color on "light".  

I can just set the background to the default light / dark control color from OS X.  Does this sound like a reasonable fix?

**Comment by voronianski** [comment]
@trevorlinton this sounds fine for me :+1: 

Actually I think that `window.extendIntoTitle = true;` is much more important feature because it actually gives you ability to customize window feel for real.

**Comment by trevorlinton** [comment]
These are now standardized for Yosemite/el Capitan and available as public properties of the Window class for both OS X/Windows (windows has a bit of a different rendering treatment thats still within the HCI guidelines for microsoft) on V2.1.20, closing out, feel free to reopen if you continue to have issues.
