### ISSUE TITLE
[minor bug] unit testing: dialog.js in win-32bit mode

### ISSUE THREAD

**Issue by petitben** [trueinteractions/tint2#85]
Hi,

I noticed the dialog.js test doesn't complete on my Win7 32bit install (64bit processor).

Actually the click on the "Do not show this again" checkbox never happens because the y position is wrong in my case what leads to an assertion error. 

I don't know if the test works correctly as it is in Win7 64bit mode but I had to modify the line 45 to make it complete:

/* @hidden */   else $utils.clickAt((scn.bounds.width/2)-95,(scn.bounds.height/2)+10); // click no supression checkbox 415,398 (cbox)

to:

/* @hidden */   else $utils.clickAt((scn.bounds.width/2)-95,(scn.bounds.height/2)+ __30__ ); // click no supression checkbox 415,398 (cbox)

**Comment by trevorlinton** [comment]
Fixed with https://github.com/trueinteractions/tint2/commit/2f434f72c643c2bd6e95aee931c1e54e22256ba3 

Instead of hard coding the value it now gets the screen's X/Y value from the control, ensuring we don't have to worry about screen resolution or window placement.  Should be fixed now, feel free to reopen if its not.  This will be included in 2.0.4 release.
