### ISSUE TITLE
app:// schema doesn't work when app is packaged and run on OSX

### ISSUE THREAD

**Issue by wwlinx** [trueinteractions/tint2#93]
I'm trying to do this:
statusBar.image = 'app://assets/statusbar_small.png';

which works fine when the app is run on the command line with "tint app.js", but doesn't work when the app is packaged and run. looks like this code in AppSchema_mac.mm:
```
	filemgr = [NSFileManager defaultManager];
	currentpath = [filemgr currentDirectoryPath];
	NSString *possible = [currentpath stringByAppendingString:url];
```

is wrong, as currentDirectoryPath is just "/".

**Comment by trevorlinton** [comment]
Fixed in https://github.com/trueinteractions/tint2/commit/02b0a54f9e4247502270f40dd85c0e1efca0cb91 and in https://github.com/trueinteractions/tint2/commit/18223b2013b1914b32bcc2e9c79d9b9e61e02797 added new unit tests for it on https://github.com/trueinteractions/tint2/commit/1ae1744d025b5b045729f9ab1857390b2af4a797

This will be in V2.0.9 release due next monday (2/9/2015).  Feel free to build it if you'd like to try it out prior to that.

**Comment by wwlinx** [comment]
awesome, thank you. will try it out
